// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFir ebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5BBFS8Xb7t1YfDu32Kv96hUzhevz44xs',
    appId: '1:1019951397287:web:771f590c61e2f88e765e82',
    messagingSenderId: '1019951397287',
    projectId: 'image-adder',
    authDomain: 'image-adder.firebaseapp.com',
    storageBucket: 'image-adder.appspot.com',
    measurementId: 'G-31E68TZDG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SRMyh-8suZUROFeGaxlPneheohrL3tU',
    appId: '1:1019951397287:android:1619866b310d97a1765e82',
    messagingSenderId: '1019951397287',
    projectId: 'image-adder',
    storageBucket: 'image-adder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZBR_dEfBXyLwEcWYg6OeWd7MVBiZ6Qo',
    appId: '1:1019951397287:ios:6573def06c62117c765e82',
    messagingSenderId: '1019951397287',
    projectId: 'image-adder',
    storageBucket: 'image-adder.appspot.com',
    iosClientId:
        '1019951397287-pjpgmr363m22ijcli5esdaupjhad21l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.edgeDetecter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZBR_dEfBXyLwEcWYg6OeWd7MVBiZ6Qo',
    appId: '1:1019951397287:ios:6573def06c62117c765e82',
    messagingSenderId: '1019951397287',
    projectId: 'image-adder',
    storageBucket: 'image-adder.appspot.com',
    iosClientId:
        '1019951397287-pjpgmr363m22ijcli5esdaupjhad21l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.edgeDetecter',
  );
}
